// =============================================================================
//  dllmain.cpp
// -----------------------------------------------------------------------------
//  Module entry point and CRT scaffolding.
//
//  The original image is built against the static CRT (/MT), which is why it
//  contains the usual library scaffolding (_security_init_cookie, the atexit
//  tables, _initterm walkers and so on) rather than importing msvcp140.dll /
//  vcruntime140.dll.  None of that is reproduced here: it is generated by the
//  toolchain and rebuilding the project with /MT recreates it byte for byte.
//
//  What does belong here is the module lifetime handling:
//
//    DLL_PROCESS_ATTACH
//        Caching the module handle and calling DisableThreadLibraryCalls().
//        The library has no per-thread state, so the thread notifications are
//        explicitly suppressed -- this is observable in the original as the
//        absence of any thread attach work.
//
//        Note that the one-time NVAPI resolution is deliberately NOT done here.
//        It happens lazily on the first Initialize() call, guarded by the
//        interlock at 0x18002029C, so that merely loading the DLL cannot fail
//        or block on a driver query.  [D]
//
//    DLL_PROCESS_DETACH
//        Reset the library state.  The detach path is also reached during
//        process termination, where the original guards its work with the
//        standard lpReserved null check.
// =============================================================================

#include "aftermath_internal.h"

#ifndef AFTERMATH_TEST_BUILD
#  include <windows.h>
#endif

#ifndef AFTERMATH_TEST_BUILD

// -----------------------------------------------------------------------------
// Module state.
// -----------------------------------------------------------------------------
static HMODULE g_hModule = nullptr;

extern "C" BOOL WINAPI DllMain(
    HINSTANCE hinstDLL,
    DWORD     fdwReason,
    LPVOID    lpvReserved)
{
    switch (fdwReason)
    {
    case DLL_PROCESS_ATTACH:
        g_hModule = static_cast<HMODULE>(hinstDLL);

        // No per-thread state exists, so skip the thread notifications.
        ::DisableThreadLibraryCalls(g_hModule);
        break;

    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
        // Suppressed by DisableThreadLibraryCalls(); listed for completeness.
        break;

    case DLL_PROCESS_DETACH:
        // lpvReserved != nullptr means the process is terminating.  Releasing
        // the library state is safe either way, but doing it during process
        // exit is pointless work: the driver may already be gone.
        if (lpvReserved == nullptr)
        {
            aftermath::Shutdown();
        }

        g_hModule = nullptr;
        break;

    default:
        break;
    }

    return TRUE;
}

#else // AFTERMATH_TEST_BUILD

// -----------------------------------------------------------------------------
// Host-side test build.
//
//   There is no loader on the test host, so expose the same lifecycle through
//   ordinary functions and let the test drive them.
// -----------------------------------------------------------------------------
namespace aftermath
{
    void TestModuleAttach()
    {
        // Mirrors the DLL_PROCESS_ATTACH arm.
    }

    void TestModuleDetach()
    {
        Shutdown();
    }
}

#endif // AFTERMATH_TEST_BUILD
