// =============================================================================
//  dllmain.cpp
// -----------------------------------------------------------------------------
//  Module entry point.
//
//  There is almost nothing to do here, and that is the whole point.  The
//  recovered DllMain is:
//
//      BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
//      {
//          return TRUE;
//      }
//
//  literally, with no switch and no body.  Everything else that a DLL would
//  normally do at attach time is absent from the image:
//
//    * no DisableThreadLibraryCalls -- the library has no per-thread state but
//      never asks to be told about threads either;
//    * no module handle caching -- nothing in the image stores its own HINSTANCE;
//    * no NVAPI resolution -- it is lazy, behind the interlock at 0x18002029C,
//      on the first Initialize() call, so merely loading the DLL can never fail
//      or block on a driver query;
//    * no teardown on detach -- there is no shutdown routine and no driver
//      release call anywhere in the listing.
//
//  The CRT scaffolding around it (_security_init_cookie, the atexit tables,
//  _initterm walkers, _DllMainCRTStartup) is generated by the toolchain and
//  reappears automatically when the project is built with /MT, so none of it is
//  reproduced here.
//
//  aftermath::Shutdown() below is therefore a reconstruction artefact rather
//  than a recovered function: it has no counterpart in the binary and exists so
//  that the host test can drive a full init/teardown cycle in one process.
// =============================================================================

#include "aftermath_internal.h"

#ifndef AFTERMATH_TEST_BUILD

#include <windows.h>

// [D] The recovered DllMain in its entirety.
extern "C" BOOL WINAPI DllMain(
    HINSTANCE hinstDLL,
    DWORD     fdwReason,
    LPVOID    lpvReserved)
{
    (void)hinstDLL;
    (void)fdwReason;
    (void)lpvReserved;

    return TRUE;
}

#else // AFTERMATH_TEST_BUILD

// -----------------------------------------------------------------------------
// Host-side test build.
//
//   There is no loader on the test host, so the (empty) lifecycle is exposed as
//   ordinary functions for the test to call.
// -----------------------------------------------------------------------------
namespace aftermath
{
    // Mirrors the DLL_PROCESS_ATTACH arm, which does nothing.
    void TestModuleAttach()
    {
    }

    // The test's stand-in for a detach path that the original does not have.
    void TestModuleDetach()
    {
        Shutdown();
    }
}

#endif // AFTERMATH_TEST_BUILD
